//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spec
    {
        public string ID { get; set; }
        public string Cod { get; set; }
        public string Name { get; set; }
        public int count_mest { get; set; }
        public string form_obuch { get; set; }
        public int cost { get; set; }
    }
}
