//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavlenie
    {
        public string ID { get; set; }
        public string number_lich_del { get; set; }
        public System.DateTime date_podachi { get; set; }
        public string time_podachi { get; set; }
        public string id_abiturienta { get; set; }
        public string vuybr_spec { get; set; }
        public string pasport { get; set; }
        public string diplom { get; set; }
        public int bals { get; set; }
    }
}
